table Client {
  IdClient: long <<PK>>
  FName: string
  MName: string
  LName: string
  Company: string
  CityClient: string
  phone: string
}


data Client {
|=IdClient |=FName |=MName |=LName |=Company |=CityClient |=phone |
| 1 | Грищенко | Петро | Васильович | ТОВ Затишок | Харків | +380502087543 |
| 2 | Кузич    | Микола | Петрович | ТОВ Дом | Київ | +380672837500 |
| 3 | Василенко | Михайло | Володимирович | Харків | +380666722565        |
| 4 | Азаренко | Тетяна | Петрівна | Львів | +380505723577|               |
| 5 | Петренко | Олена | Миколаївна | Львів |  |                          |
| 6 | Бобир | Олексій  | Іванович | Ужгород | +380676757755 |             |
| 7 | Хрущ | Єгор | Петрович | Чернівці |  |                              |
}