FROM sytoss/openjdk:17-alpine

RUN groupadd stpuser
RUN useradd -r -g stpuser stpuser

USER stpuser

ADD /target/*.jar /jar/stp-ms-test=producer.jar

EXPOSE 9104

ENTRYPOINT [ "java","-jar","/jar/stp-ms-test=producer.jar" ]