image: maven:3.8.5-openjdk-17

pipelines:

  branches:
    develop:
      - step:
          name: Build and push
          script:
            - mvn clean install
            - export VERSION=$(cat pom.xml | grep "<version>" | sed -e '1!d' | sed -e '1!d' | sed 's/.*<version>//g' | sed 's/<.*//g' | tr -d '\n\r' )
            - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD docker.io
            - docker build -t sytoss/image-provider:$(echo $VERSION) -f ./docker/Dockerfile .
            - docker push sytoss/image-provider:$(echo $VERSION)
            - docker system prune -a -f
          services:
            - docker