image: maven:3.8.5-openjdk-17

pipelines:

  branches:
    release-1.2.x:
      - step:
          name: Build and push
          script:
            - mvn clean install
            - echo $(cat pom.xml | grep "<version>" | sed -e '1!d' | sed -e '1!d' | sed 's/.*<version>//g' | sed 's/<.*//g' | tr -d '\n\r' )
            - export VERSION=$(cat pom.xml | grep "<version>" | sed -e '1!d' | sed -e '1!d' | sed 's/.*<version>//g' | sed 's/<.*//g' | tr -d '\n\r' )
            - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD docker.io
            #            - docker build -t sytoss/graphiz:latest -f ./stp-common/src/main/docker/Dockerfile .
            #            - docker push sytoss/graphiz:latest
            - docker build -t sytoss/stp-ms-check-task:$(echo $VERSION) -f ./stp-ms-check-task/src/main/docker/Dockerfile .
            - docker build -t sytoss/stp-ms-test-producer:$(echo $VERSION) -f ./stp-ms-test-producer/src/main/docker/Dockerfile .
            - docker build -t sytoss/stp-ms-lessons:$(echo $VERSION) -f ./stp-ms-lessons/src/main/docker/Dockerfile .
            - docker build -t sytoss/stp-ms-users:$(echo $VERSION) -f ./stp-ms-users/src/main/docker/Dockerfile .
            - docker push sytoss/stp-ms-check-task:$(echo $VERSION)
            - docker push sytoss/stp-ms-test-producer:$(echo $VERSION)
            - docker push sytoss/stp-ms-lessons:$(echo $VERSION)
            - docker push sytoss/stp-ms-users:$(echo $VERSION)
            - docker system prune -a -f
          services:
            - docker
    release(SNAPSHOT removing):
      - step:
          name: Build and push
          script:
            - git config --global user.email $EMAIL
            - mvn clean install -DskipTests -Darguments=-DskipTests
            - echo $(cat pom.xml | grep "<version>" | sed -e '1!d' | sed -e '1!d' | sed 's/.*<version>//g' | sed 's/<.*//g' | tr -d '\n\r' )
            - export VERSION=$(cat pom.xml | grep "<version>" | sed -e '1!d' | sed -e '1!d' | sed 's/.*<version>//g' | sed 's/<.*//g' | sed 's/-SNAPSHOT//g' | tr -d '\n\r' )
            - export NEWVERS=$(./version.sh -p ${VERSION} | tr -d '\r\n')
            - mvn --batch-mode -DskipTests -Darguments=-DskipTests release:prepare -DscmCommentPrefix="[skip ci]" -Dtag="${VERSION}"  -DreleaseVersion="${VERSION}" -DdevelopmentVersion="${NEWVERS}-SNAPSHOT"
            - mvn release:perform -Darguments="-Dmaven.deploy.skip=true" -DscmCommentPrefix="[skip ci]"
            - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD docker.io
            #            - docker build -t sytoss/graphiz:latest -f ./stp-common/src/main/docker/Dockerfile .
            #            - docker push sytoss/graphiz:latest
            - docker build -t sytoss/stp-ms-check-task:$(echo $VERSION) -f ./stp-ms-check-task/src/main/docker/Dockerfile .
            - docker build -t sytoss/stp-ms-test-producer:$(echo $VERSION) -f ./stp-ms-test-producer/src/main/docker/Dockerfile .
            - docker build -t sytoss/stp-ms-lessons:$(echo $VERSION) -f ./stp-ms-lessons/src/main/docker/Dockerfile .
            - docker build -t sytoss/stp-ms-users:$(echo $VERSION) -f ./stp-ms-users/src/main/docker/Dockerfile .
            - docker push sytoss/stp-ms-check-task:$(echo $VERSION)
            - docker push sytoss/stp-ms-test-producer:$(echo $VERSION)
            - docker push sytoss/stp-ms-lessons:$(echo $VERSION)
            - docker push sytoss/stp-ms-users:$(echo $VERSION)
            - docker system prune -a -f
          services:
            - docker
    path:
      - step:
          name: Build and push
          script:
            - git config --global user.email $EMAIL
            - mvn clean install -DskipTests -Darguments=-DskipTests
            - echo $(cat pom.xml | grep "<version>" | sed -e '1!d' | sed -e '1!d' | sed 's/.*<version>//g' | sed 's/<.*//g' | tr -d '\n\r' )
            - export OLDVERSION=$(cat pom.xml | grep "<version>" | sed -e '1!d' | sed -e '1!d' | sed 's/.*<version>//g' | sed 's/<.*//g' | sed 's/-SNAPSHOT//g' | tr -d '\n\r' )
            - export VERSION=$(./version.sh -p ${OLDVERSION} | tr -d '\r\n')
            - export NEWVERS=$(./version.sh -p ${VERSION} | tr -d '\r\n')
            - mvn --batch-mode -DskipTests -Darguments=-DskipTests release:prepare -DscmCommentPrefix="[skip ci]" -Dtag="${VERSION}"  -DreleaseVersion="${VERSION}" -DdevelopmentVersion="${NEWVERS}-SNAPSHOT"
            - mvn release:perform -Darguments="-Dmaven.deploy.skip=true" -DscmCommentPrefix="[skip ci]"
            - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD docker.io
            #            - docker build -t sytoss/graphiz:latest -f ./stp-common/src/main/docker/Dockerfile .
            #            - docker push sytoss/graphiz:latest
            - docker build -t sytoss/stp-ms-check-task:$(echo $VERSION) -f ./stp-ms-check-task/src/main/docker/Dockerfile .
            - docker build -t sytoss/stp-ms-test-producer:$(echo $VERSION) -f ./stp-ms-test-producer/src/main/docker/Dockerfile .
            - docker build -t sytoss/stp-ms-lessons:$(echo $VERSION) -f ./stp-ms-lessons/src/main/docker/Dockerfile .
            - docker build -t sytoss/stp-ms-users:$(echo $VERSION) -f ./stp-ms-users/src/main/docker/Dockerfile .
            - docker push sytoss/stp-ms-check-task:$(echo $VERSION)
            - docker push sytoss/stp-ms-test-producer:$(echo $VERSION)
            - docker push sytoss/stp-ms-lessons:$(echo $VERSION)
            - docker push sytoss/stp-ms-users:$(echo $VERSION)
            - docker system prune -a -f
          services:
            - docker
    minor:
      - step:
          name: Build and push
          script:
            - git config --global user.email $EMAIL
            - mvn clean install -DskipTests -Darguments=-DskipTests
            - echo $(cat pom.xml | grep "<version>" | sed -e '1!d' | sed -e '1!d' | sed 's/.*<version>//g' | sed 's/<.*//g' | tr -d '\n\r' )
            - export OLDVERSION=$(cat pom.xml | grep "<version>" | sed -e '1!d' | sed -e '1!d' | sed 's/.*<version>//g' | sed 's/<.*//g' | sed 's/-SNAPSHOT//g' | tr -d '\n\r' )
            - export VERSION=$(./version.sh -m ${OLDVERSION} | tr -d '\r\n')
            - export NEWVERS=$(./version.sh -p ${VERSION} | tr -d '\r\n')
            - mvn --batch-mode -DskipTests -Darguments=-DskipTests release:prepare -DscmCommentPrefix="[skip ci]" -Dtag="${VERSION}"  -DreleaseVersion="${VERSION}" -DdevelopmentVersion="${NEWVERS}-SNAPSHOT"
            - mvn release:perform -Darguments="-Dmaven.deploy.skip=true" -DscmCommentPrefix="[skip ci]"
            - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD docker.io
            #            - docker build -t sytoss/graphiz:latest -f ./stp-common/src/main/docker/Dockerfile .
            #            - docker push sytoss/graphiz:latest
            - docker build -t sytoss/stp-ms-check-task:$(echo $VERSION) -f ./stp-ms-check-task/src/main/docker/Dockerfile .
            - docker build -t sytoss/stp-ms-test-producer:$(echo $VERSION) -f ./stp-ms-test-producer/src/main/docker/Dockerfile .
            - docker build -t sytoss/stp-ms-lessons:$(echo $VERSION) -f ./stp-ms-lessons/src/main/docker/Dockerfile .
            - docker build -t sytoss/stp-ms-users:$(echo $VERSION) -f ./stp-ms-users/src/main/docker/Dockerfile .
            - docker push sytoss/stp-ms-check-task:$(echo $VERSION)
            - docker push sytoss/stp-ms-test-producer:$(echo $VERSION)
            - docker push sytoss/stp-ms-lessons:$(echo $VERSION)
            - docker push sytoss/stp-ms-users:$(echo $VERSION)
            - docker system prune -a -f
          services:
            - docker
    major:
      - step:
          name: Build and push
          script:
            - git config --global user.email $EMAIL
            - mvn clean install -DskipTests -Darguments=-DskipTests
            - echo $(cat pom.xml | grep "<version>" | sed -e '1!d' | sed -e '1!d' | sed 's/.*<version>//g' | sed 's/<.*//g' | tr -d '\n\r' )
            - export OLDVERSION=$(cat pom.xml | grep "<version>" | sed -e '1!d' | sed -e '1!d' | sed 's/.*<version>//g' | sed 's/<.*//g' | sed 's/-SNAPSHOT//g' | tr -d '\n\r' )
            - export VERSION=$(./version.sh -M ${OLDVERSION} | tr -d '\r\n')
            - export NEWVERS=$(./version.sh -p ${VERSION} | tr -d '\r\n')
            - mvn --batch-mode -DskipTests -Darguments=-DskipTests release:prepare -DscmCommentPrefix="[skip ci]" -Dtag="${VERSION}"  -DreleaseVersion="${VERSION}" -DdevelopmentVersion="${NEWVERS}-SNAPSHOT"
            - mvn release:perform -Darguments="-Dmaven.deploy.skip=true" -DscmCommentPrefix="[skip ci]"
            - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD docker.io
            #            - docker build -t sytoss/graphiz:latest -f ./stp-common/src/main/docker/Dockerfile .
            #            - docker push sytoss/graphiz:latest
            - docker build -t sytoss/stp-ms-check-task:$(echo $VERSION) -f ./stp-ms-check-task/src/main/docker/Dockerfile .
            - docker build -t sytoss/stp-ms-test-producer:$(echo $VERSION) -f ./stp-ms-test-producer/src/main/docker/Dockerfile .
            - docker build -t sytoss/stp-ms-lessons:$(echo $VERSION) -f ./stp-ms-lessons/src/main/docker/Dockerfile .
            - docker build -t sytoss/stp-ms-users:$(echo $VERSION) -f ./stp-ms-users/src/main/docker/Dockerfile .
            - docker push sytoss/stp-ms-check-task:$(echo $VERSION)
            - docker push sytoss/stp-ms-test-producer:$(echo $VERSION)
            - docker push sytoss/stp-ms-lessons:$(echo $VERSION)
            - docker push sytoss/stp-ms-users:$(echo $VERSION)
            - docker system prune -a -f
          services:
            - docker
