@startuml

entity Discipline #red{
id: long
name: string
}

entity Topic #red{
id: long
name: string
}

entity Task  #red{
id: long
question: string
answer: string
}

entity Condition  #red{
id: long
name: string
}

entity TaskDomain  #red{
id: long
name: string
script: string
}

entity Exam  #red{
id: long
name: string
}

entity PersonalExam {
id: long
name: string
date: date
}

entity Answer {
id: long
question: string
value: string
}

enum PersonalExamStatus{
In Progress,
Not Started,
Finished
}

enum AnswerStatus{
In Progress,
Not Started,
Answered,
Graded
}

entity Grade{
id: long
value: int
comment: string
}

entity Student #red{
id: long
name: string
middlename: string
lastname: string
email:string
password:string
group:string
photo:?
}

entity Teacher #red{
id: long
name: string
middlename: string
lastname: string
email:string
password:string
photo:?
}

entity Group #red{
id: long
name: string
}

entity ExamParameter #red{
id: long
countOfTask: int
}

ExamParameter "N examParameter" --o "1" Exam
Topic "1" --o "1" ExamParameter
Answer o-- AnswerStatus
PersonalExam o-- PersonalExamStatus
PersonalExam "1" o-- "N answers" Answer
Task "1" --o "1" Answer
Grade "1" --o "1" Answer
Student "1" --o "1" PersonalExam
Task "1" o-- "N conditions" Condition
Task "N tasks" o--o "N topics" Topic
Task "1" o-- "1" TaskDomain
Task "N tasks" --o "1" PersonalExam
Student "1" --o "N groups" Group

Exam "1" --o "N personalExams" PersonalExam

Discipline "1" o-- "N topics" Topic
Discipline "N disciplines" o-- "1" Teacher
@enduml