@startuml

entity Discipline #red{
id: long
name: string
}

entity Topic #red{
id: long
name: string
}

entity Task  #red{
id: long
question: string
answer: string
}

entity Condition  #red{
id: long
name: string
}

entity TaskDomain  #red{
id: long
name: string
script: string
}

entity Test  #red{
id: long
name: string
}

entity PersonalTest {
id: long
name: string
date: date
}

entity Answer {
id: long
quastion: string
answer: string
}

enum Status{
In Progress,
Not Started,
Finished
}

entity Grade{
id: long
grade: int
comment: string
}

entity Student{
id: long
name: string
}

entity TestParameter #red{
id: long
countOfTask: int
}

TestParameter "N testParameter" --o "1" Test
Topic "1" --o "1" TestParameter
Answer o-- Status
PersonalTest o-- Status
PersonalTest "1" o-- "N answers" Answer
Task "1" --o "1" Answer
Grade "1" --o "1" Answer
Student "1" --o "1" PersonalTest
Task "1" o-- "N conditions" Condition
Task "N tasks" o--o "N topics" Topic
Task "1" o-- "1" TaskDomain
Task "N tasks" --o "1" PersonalTest


Test "1" --o "N personalTests" PersonalTest

Discipline "1" o-- "N topics" Topic

@enduml