version: '3.7'
services:
  postgres:
    image: postgres
    #volumes:
    #  - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3
    volumes:
      - ./keycloak/imports:/opt/keycloak/data/import
      - ./keycloak/themes/custom:/opt/keycloak/themes/custom
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_SCHEMA: public
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: Pa55w0rd
    ports:
      - 9080:8080
    depends_on:
      - postgres
    command:
      - start-dev --import-realm

