FROM sytoss/openjdk:17-alpine

RUN groupadd stpuser
RUN useradd -r -g stpuser stpuser

USER stpuser

ADD /target/*.jar /jar/stp-ms-user.jar

EXPOSE 9105

ENTRYPOINT [ "java","-jar","/jar/stp-ms-user.jar" ]