version: "3.9"
services:
  postgres:
    container_name: postgres_users
    image: postgres:13.3
    environment:
      POSTGRES_DB: "users"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"