server:
  port: ${APP_PORT:9010}
logging:
  level:
    root: ${APP_LOG:INFO}
    de:
      flapdoodle: WARN
    sun:
      rmi: WARN
    org:
      springframework: WARN
      mongodb: WARN
    liquibase: ERROR
custom:
  executor:
    username: ${EXE_USERNAME:admin}
    password: ${EXE_PASSWORD:password}
    serverPath: ${EXE_SERVER:192.168.160.26:8432/db}
    executorType: ${EXE_TYPE:POSTGRESQL}
    poolSize: 20
#feign:
#  client:
#    config:
#      default:
#        loggerLevel: FULL
