server:
  port: ${APP_PORT:9103}
spring:
  data:
    mongodb:
      uri: ${DB_URI:mongodb://admin:pwd@127.0.0.1:27017/stp?authSource=admin}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9080/realms/stp/protocol/openid-connect/certs
check-task-url: http://localhost:9010/api/