server:
  port: ${APP_PORT:9103}
spring:
  data:
    mongodb:
      uri: ${DB_URI:mongodb://admin:pwd@127.0.0.1:27017/stp?authSource=admin}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_URI:http://localhost:9080/realms/stp/protocol/openid-connect/certs}
check-task-url: ${CHECK_TASK_URI:http://localhost:9010/api/}
lessons-url: ${LESSONS_URI:http://localhost:9101/api/}