@startuml
entity Discipline #red{
id: long
name: string
}

entity Topic #red{
id: long
name: string
}

entity Task  #red{
id: long
question: string
answer: string
}

Discipline "1" --o "N topics" Topic
Discipline "1" --o "1" Task
Topic "N topics" o--o "N tasks" Task
@enduml