spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URI:jdbc:postgresql://localhost:7432/lessons}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
        ddl-auto: validate
  liquibase:
    change-log: classpath:/liquibase/db.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9080/realms/stp/protocol/openid-connect/certs
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        request-interceptors[0]: com.sytoss.lessons.controllers.TokenRequestInterceptor
server:
   port: 9101
users-url: http://localhost:9102/api/
check-task-url: http://localhost:9010/api/