server:
  port: ${APP_PORT:9101}
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URI:jdbc:postgresql://192.168.160.26:7432/lessons}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
        ddl-auto: validate
  liquibase:
    change-log: classpath:/liquibase/db.changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_URI:https://stp.sytoss.intra/realms/stp/protocol/openid-connect/certs}
  jackson:
    default-property-inclusion: non_null
feign:
  client:
    config:
      default:
        #        loggerLevel: FULL
        connectTimeout: 5000
        readTimeout: 5000
        request-interceptors[0]: com.sytoss.lessons.controllers.TokenRequestInterceptor
users-url: ${USER_URI:https://stp.sytoss.intra/api}
test-producer-url: ${TEST_PRODUCER_URI:https://stp.sytoss.intra/api}
check-task-url: ${CHECK_TASK_URI:https://stp.sytoss.intra/api}
image-provider-url: ${IMAGE_PROVIDER_URL:https://stp.sytoss.intra/api}
logging:
  level:
    root: ${APP_LOG:INFO}
    de:
      flapdoodle: WARN
    sun:
      rmi: WARN
    org:
      springframework: WARN
      mongodb: WARN
      hibernate: WARN
    liquibase: WARN
