server:
  port: ${APP_PORT:9102}
spring:
  servlet:
    multipart:
      max-request-size: 4MB
      max-file-size: 4MB
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URI:jdbc:postgresql://localhost:6432/users}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
        ddl-auto: validate
  liquibase:
    change-log: classpath:/liquibase/db.changelog-master1.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_URI:http://localhost:9080/realms/stp/protocol/openid-connect/certs}
registration:
  allow-registration: ${ALLOW_TEACHER_REGISTRATION:true}
logging:
  level:
    root: ${APP_LOG:INFO}
    de:
      flapdoodle: WARN
    sun:
      rmi: WARN
    org:
      springframework: WARN
      mongodb: WARN
    liquibase: WARN
#feign:
#  client:
#    config:
#      default:
#        loggerLevel: FULL
image-provider-url: ${IMAGE_PROVIDER_URL:http://localhost:9204/api}