server:
  port: ${APP_PORT:9102}
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DB_URI:jdbc:postgresql://localhost:6432/users}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgresPlusDialect
        ddl-auto: validate
  liquibase:
    change-log: classpath:/liquibase/db.changelog-master1.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9080/realms/stp/protocol/openid-connect/certs