entity Discipline {
id: long <<PK>>
name: string
}

entity Topic {
id: long <<PK>>
name: string
discipline_id: long <<FK Discipline(id)>>
}

entity Task {
id: long <<PK>>
question: string
answer: string
discipline_id: long <<FK Discipline(id)>>
}

entity TopicToTask {
task_id: long <<PK>>
topic_id: long <<PK>>
}

object "Data:Discipline" as dDiscipline {
   |= id |= name |
   | 1   | SQL   |
   | 2   | Mongo  |
}

object "Data:Topic" as dTopic {
   |= id |= name    |= discipline_id |
   | 1   | Insert   |        1       |
   | 2   | Select   |        2       |
   | 3   | Join     |        1       |
}

object "Data:Task" as dTask {
   |= id |= question                |= discipline_id |
   | 1   | What is Join?            |        1       |
   | 2   | What is Inner Join?      |        1       |
   | 3   | What is Join?            |        1       |
   | 4   | What is Select?          |        2       |
}

object "Data:Topic" as dTopicToTask {
   |= task_id |= topic_id |
   | 1        | 1         |
   | 2        | 3         |
   | 3        | 2         |
   | 4        | 1         |
}