version: '3.7'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    ports:
      - 9201:9200
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xss1024K -Xmx1G"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - elasticsearch_logs:/usr/share/elasticsearch/logs
  tomcat:
    image: craftercms/authoring_tomcat:4.0.3 # craftercms version flag
    depends_on:
      - elasticsearch
      - deployer
    ports:
      - 8080:8080
    volumes:
      - crafter_data:/opt/crafter/data
      - crafter_logs:/opt/crafter/logs
      - crafter_temp:/opt/crafter/temp
      # Elastic Search dirs needed for backup/restore
      - elasticsearch_data:/opt/crafter/data/indexes-es
    environment:
      - DEPLOYER_HOST=deployer
      - DEPLOYER_PORT=9191
      - ES_HOST=elasticsearch
      - ES_PORT=9200
  deployer:
    image: craftercms/deployer:4.0.3 # craftercms version flag
    depends_on:
      - elasticsearch
    ports:
      - 9191:9191
    volumes:
      - crafter_data:/opt/crafter/data
      - crafter_logs:/opt/crafter/logs
      - crafter_temp:/opt/crafter/temp
    environment:
      - TOMCAT_HOST=tomcat
      - TOMCAT_HTTP_PORT=8080
      - ES_HOST=elasticsearch
      - ES_PORT=9200
volumes:
  elasticsearch_data:
    name: crafter_authoring_data_elasticsearch
  elasticsearch_logs:
    name: crafter_authoring_logs_elasticsearch
  crafter_data:
    name: crafter_authoring_data
  crafter_logs:
    name: crafter_authoring_logs
  crafter_temp:
    name: crafter_authoring_temp
